CREATE TABLE Menu
(
	Id INT NOT NULL IDENTITY(1,1),
	Nama NVARCHAR(MAX) NULL,
	Deskripsi NVARCHAR(MAX) NULL,
	Metode NVARCHAR(MAX) NULL,
	Kategori NVARCHAR(MAX) NULL,
	Harga float NULL,
	Diskon float NULL
)

ALTER TABLE Menu ADD PRIMARY KEY (Id)

CREATE TABLE Transaksi
(
	Id INT NOT NULL IDENTITY(1,1),
	Pelanggan NVARCHAR(MAX) NULL,
	Tanggal DATETIME NULL,
	MenuPelanggan NVARCHAR(MAX) NULL,
	Diskon FLOAT NULL,
	TotalHarga FLOAT NULL,
)

ALTER TABLE Transaksi ADD PRIMARY KEY (Id)

CREATE TABLE Metode
(
	Id INT NOT NULL IDENTITY(1,1),
	Nama NVARCHAR(MAX) NULL,
	Harga FLOAT NULL
)

ALTER TABLE Metode ADD PRIMARY KEY (Id)

CREATE TABLE [User]
(
	Id INT NOT NULL IDENTITY(1,1),
	Nama NVARCHAR(MAX) NULL,
	[Password] NVARCHAR(MAX) NULL,
	Access NVARCHAR(MAX) NULL
)

ALTER TABLE [User] ADD PRIMARY KEY (Id)

